stages:
  - ping
  - build

ping_job:
  stage: ping
  script:
    - echo 'start'
  tags:
    - imgker

build_job:
  stage: build
  script:
    - npm install
    - npm run build 
    - APPID=$(NODE_ENV=$(git log --pretty=format:\"%an-%h-%s-%H\" -1) node ./gitlab-ci/init.js)
    - mkdir dist_new
    - mv ./dist ./dist_new 
    # - mv ./dist_new /home
    - ossutil64 cp -r ./dist_new oss://jsonote/$APPID  > logg.txt
  tags:
    - imgker
