stages:
  - build
  - cleanup_build
  - test
  - deploy
  - cleanup

build_job:
  stage: build
  script:
    - npm set registry https://registry.npm.taobao.org
    - pwd
    - npm install --progress=false
    - npm run build
  tags:
    - imgker

cleanup_build_job:
  stage: cleanup_build
  script:
    - echo $PWD
  when: on_failure
  tags:
    - imgker

test_job:
  stage: test
  script:
    - echo $PWD
  tags:
    - imgker

deploy_job:
  stage: deploy
  script:
    - echo $PWD
  when: manual
  tags:
    - imgker

cleanup_job:
  stage: cleanup
  script:
    - echo $PWD
  when: always
  tags:
    - imgker
 