stages:
  - build
  - deploy
  - upload

build_job:
  stage: build
  script:
    - npm install
    - npm run build 
  tags:
    - imgker

deploy_job:
  stage: deploy
  script:
    - APPID=$(NODE_ENV=$(git log --pretty=format:\"%an-%h-%s-%H\" -1) node ./gitlab-ci/init.js)
    - mkdir dist_new
    - mv ./dist ./dist_new 
    - mv ./dist_new /home
  tags:
    - imgker

upload_job:
  stage: upload
  script:
    - /home/ossutil64 cp -r /home/dist_new oss://jsonote/$APPID
  tags:
    - imgker 
